<a href="https://colab.research.google.com/github/naiksahana/pandas-and-numpy-internship/blob/main/Copy_of_Solution_week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Import libraries

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
file_path = '/content/drive/My Drive/Data-cleaning-for-beginners-using-pandas (1).csv'

In [ ]:
data = pd.read_csv(file_path)

## Load data

- head()
- tail()
- info()
- dtypes()
- describe()
- shape

In [ ]:
data.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
data.tail()

    Index   Age     Salary  Rating       Location  Established Easy Apply
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0  $44k-$99k     5.4       India,In         1935         -1
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
data.sample(3)

    Index   Age     Salary  Rating     Location  Established Easy Apply
5       5  44.0  $77k-$89k     1.4     India,In         1999       TRUE
11     11  44.0  $10k-$49k     6.7     India,In         2009         -1
19     19  32.0  $44k-$99k     3.3  New York,Ny         1955       TRUE

In [ ]:
data.shape

(29, 7)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

In [ ]:
data.isna().sum()

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [ ]:
data.columns

Index(['Index', 'Age', 'Salary', 'Rating', 'Location', 'Established',
       'Easy Apply'],
      dtype='object')

In [ ]:
data.columns = data.columns.str.lower().str.replace(' ','_')

In [ ]:
data.head()

   index   age     salary  rating       location  established easy_apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

# Age

In [ ]:
avg_age = data.age.mean()

In [ ]:
data['age'] = data['age'].fillna(avg_age)
data['age'] = data['age'].round(decimals=1)
data['age']

0     44.0
1     66.0
2     39.0
3     64.0
4     25.0
5     44.0
6     21.0
7     44.0
8     35.0
9     22.0
10    55.0
11    44.0
12    39.0
13    25.0
14    66.0
15    44.0
16    19.0
17    39.0
18    35.0
19    32.0
20    39.0
21    35.0
22    19.0
23    39.0
24    13.0
25    55.0
26    39.0
27    52.0
28    39.0
Name: age, dtype: float64

In [ ]:
data['age'].isna().sum()

0

# Salary

In [ ]:
data['salary'] = data['salary'].apply(lambda x:x.replace('$',''))
data['salary'] = data['salary'].apply(lambda x:x.replace('k','000'))

In [ ]:
data['salary']

0      44000-99000
1      55000-66000
2      77000-89000
3      44000-99000
4      44000-99000
5      77000-89000
6      44000-99000
7      44000-99000
8      44000-99000
9      44000-99000
10     10000-49000
11     10000-49000
12     44000-99000
13     44000-99000
14     44000-99000
15    88000-101000
16     19000-40000
17     44000-99000
18     44000-99000
19     44000-99000
20     44000-99000
21     44000-99000
22     55000-66000
23     44000-99000
24     44000-99000
25     44000-99000
26     55000-66000
27     44000-99000
28     39000-88000
Name: salary, dtype: object

In [ ]:
data.head()

   index   age       salary  rating       location  established easy_apply
0      0  44.0  44000-99000     5.4       India,In         1999       TRUE
1      1  66.0  55000-66000     3.5    New York,Ny         2002       TRUE
2      2  39.0  77000-89000    -1.0    New York,Ny           -1         -1
3      3  64.0  44000-99000     4.4       India In         1988         -1
4      4  25.0  44000-99000     6.4  Australia Aus         2002         -1

In [ ]:
data['age'] = data['age'].astype(int)

established

In [ ]:
data['established'].isna().sum()

0

In [ ]:
import pandas as pd

# Assuming 'data' is your pandas DataFrame

# Convert the 'established' column to numeric data type
data['established'] = pd.to_numeric(data['established'], errors='coerce')

# Fill NaN values with the mean and round to one decimal place
data['established'] = data['established'].fillna(data['established'].mean()).round(decimals=1)

# Print the converted and processed 'established' column
print(data['established'])

0     1999.0
1     2002.0
2     1980.2
3     1988.0
4     2002.0
5     1999.0
6     1980.2
7     1980.2
8     1980.2
9     1980.2
10    2008.0
11    2009.0
12    1999.0
13    2019.0
14    2020.0
15    1999.0
16    1984.0
17    1943.0
18    1954.0
19    1955.0
20    1944.0
21    1946.0
22    1988.0
23    1999.0
24    1987.0
25    1980.0
26    1934.0
27    1935.0
28    1932.0
Name: established, dtype: float64

rating

In [ ]:
data['rating'].isna().sum()

0

In [ ]:
[15,10,15,5,12,90]

[15, 10, 15, 5, 12, 90]

Data Types:

In [ ]:
data.dtypes

index              int64
age                int64
salary            object
rating           float64
established       object
easy_apply        object
location_city     object
city_sign         object
dtype: object

easy apply

In [ ]:
data['easy_apply'] = data['easy_apply'].apply(lambda x:x.replace('-1','FALSE'))
print(data['easy_apply'])

0      TRUE
1      TRUE
2     FALSE
3     FALSE
4     FALSE
5      TRUE
6     FALSE
7     FALSE
8     FALSE
9      TRUE
10     TRUE
11    FALSE
12    FALSE
13     TRUE
14     TRUE
15    FALSE
16    FALSE
17     TRUE
18     TRUE
19     TRUE
20     TRUE
21    FALSE
22     TRUE
23     TRUE
24    FALSE
25     TRUE
26     TRUE
27    FALSE
28    FALSE
Name: easy_apply, dtype: object

Location column:

cleaning the location and splitting the city from the city short name

In [ ]:
#cleaning the location and splitting the city from the city short name
data['location']=data['location'].str.replace("Australia Aus","Austalia.Aus")
data['location_city']=data['location'].str.split(",",expand=True).get(0)
data['city_sign']=data['location'].str.split(",",expand=True).get(1)
data.drop('location',inplace=True,axis=1)

Rating column

In [ ]:
data['rating'].isna().sum()

0

In [ ]:
data['rating']=data["rating"].replace(-1,np.nan)
data['rating']=data["rating"].fillna(data['rating'].mean()).round(decimals=1)
print(data['rating'])

0     5.4
1     3.5
2     4.3
3     4.4
4     6.4
5     1.4
6     0.0
7     4.3
8     5.4
9     7.7
10    5.4
11    6.7
12    0.0
13    4.3
14    4.0
15    3.0
16    4.5
17    5.3
18    6.7
19    3.3
20    5.7
21    5.0
22    7.8
23    2.4
24    4.3
25    0.0
26    4.3
27    5.4
28    3.4
Name: rating, dtype: float64